### ISSUE TITLE
Custom statusline doesn't render background correctly and is the wrong size

### ISSUE THREAD

**Issue by akinsho** [windwp/floatline.nvim#1]
Hi @windwp,

just wanted to give this a quick try out of curiousity and ran into some issue with the rendering. I don't use a statusline plugin and create my own statusline but noticed some strangeness in the rendering. it seems to not have any spacing between section. I include a middle separator but don't currently put any items in the middle (not sure if that is relevant). I also change the background of the whole statusline to be darker than the Normal background color which seems to also not work.

I'm raising this more as an FYI than anything else since personally I'm probably going to hold out till this is a native feature as having to work out how to hide the statusline in splits is a pain 😅 

### Appearance with Floatline

<img width="2560" alt="Screen Shot 2021-09-29 at 11 10 05" src="https://user-images.githubusercontent.com/22454918/135249117-330de361-f012-4582-a2fd-6708548e9a02.png">

### Appearance normally
<img width="2560" alt="Screen Shot 2021-09-29 at 11 11 10" src="https://user-images.githubusercontent.com/22454918/135249273-546801a2-324a-4352-9c4e-975f39f6ca67.png">

Full statusline string
```
"%#StIndicator#▌%* %#StModeCommand#COMMAND%* %#DevIconLuaStatusline# %#StDirectory#.c/n/lua/%*%#StParentDirectory#as/%*%#StFilename#statusline.lua%*%=%=%#StGit# %#StBlue#main%* %#StGreen# %#StTitle#1%*  %#StMetadataPrefix#ℓ %#StTitle#96%#StComment#
/%#StComment#362 %<"
```

**Comment by windwp** [comment]
i really want to help but i only public it. @shadmansaleh  gave me that ffi Code :(
seriously on windline I don't use ffi code I render from component to text and convert %= to space and it has better speed.

I know you create your own statusline maybe you can try to do that. Hiding the default active statusline is not difficult I just spam ____ on that window.

I really like a new floatline.  you can try windline and open telescope that statusline still there the mode is on insert mode it display the information on the last window but the line,col is belonged to a floating window.

**Comment by akinsho** [comment]
@windwp tbh it's not a big deal at all I only mentioned just so you were aware of potential issues, I'm personally going to wait however long it is for this functionality to be native but I was just curious about how this plugin would behave.

Tbh it seems like it would almost be better to be more opinionated about this and just provide an api for a statusline the way that statusline plugins do and just render that at the bottom and then override all other statuslines. Ofc this would mean it didn't pick up the standard statusline syntax but 🤷🏿‍♂️

**Comment by shadmansaleh** [comment]
I think the background is different because it's using float bg . winhl options should be used to bind it to Statusline hl group .

`%=` worked at lest on my version I haven't tested this not sure what's going on here.

Inactive statusline probably can't be handled by this plugin without statuslines co-operation . (Most stl plugin will just fight over the stl option if this plugin tries to overwrite it 🤷‍♂️)

This was in really highly experimental stage . It was just a POC for the idea this wasn't really  to be released at this stage IMO. Hack I didn't even handle memory nor did I check if it's leaking any (which probably it is considering my previous experience with ffi 🤔).

I had specifically said this had lots of glitches and wasn't ready for regular use. @windwp it's on you for releasing it in this stage😁

**Comment by windwp** [comment]
@shadmansaleh 😅😅😅

I will update on readme to tell that. I check ffi function on neovim codebase but i am not familiar with c enough understand how to debug that.

It is my fault i should not public that code i don't understand.
i test on airline lightline and lualine a bit and it is working.
maybe because on lualine you use %{} not %!


on ffi function it has a variable cur_win and max_width and i am not using it.

I still prefer lua plugin use lua to convert. it is not hard to map syntax %f or %c to a real value on lua.

**Comment by windwp** [comment]
@akinsho 
are you try to test by call the ffi function directly.  something like %!v.lua.... maybe not working
it have a different window id to the current window.

**Comment by shadmansaleh** [comment]
> maybe because on lualine you use %{} not %!

I don't think that's the case . windline uses %! right ? also feline uses %! too IIRC they worked too when I tested on my implementation before sharing it on matrix . So %! can't be the reason . Maybe I check it out what's broken after I'm through my exams .

Also on that note why are you still using %!expr ? %{%expr%} is better it's like a merge of both %! & %{} (I had added it because both %! & %{} had their own set of limitation) maybe check it out when you get time :D

**Comment by windwp** [comment]
@shadmansaleh 
i use with %!v.lua.abcde(bufnr,winid) and i am not call something like get_buf or get_win inside it.

**Comment by akinsho** [comment]
> are you try to test by call the ffi function directly

Nope hadn't tried that, I've not used ffi with lua tbh not sure what exactly to call

> Also on that note why are you still using %!expr ? %{%expr%} is better it's like a merge of both %! & %{} (I had added it because both %! & %{} had their own set of limitation) maybe check it out when you get time :D

Haven't seen the need to change, I saw the PR go in but wasn't particularly keen to resturcture/rewrite my statusline 🤷🏿 (if it ain't broke etc.)

**Comment by shadmansaleh** [comment]
@akinsho by any chance are you using M1 mac?

Also what arch, os, terminal, neovim version are you using when this bug occurs?

> I saw the PR go in but wasn't particularly keen to resturcture/rewrite my statusline 🤷🏿 (if it ain't broke etc.)

Makes sense . In short %!expr gets evaluated in active windows context and %{expr} gets evaluated in statusline windows context . $!expr requires a lot of hoops when you want info on statusline window instead of active one and issue with %{}
 is that those expressions returning stl formats like %f or %#hl# doesn't get evaluated . %{%expr%} gets evaluated on statusline windows context and expressions returned by that expr also gets evaluated.

**Comment by akinsho** [comment]
@shadmansaleh I'm on both a mac (intel) and an ubuntu (intel) machine, but tested this on the mac and saw the issue didn't try on ubuntu (will try and see since that's on nvim nightly). I use kitty terminal and nvim 5.1 on the mac.

I definitely see the value of the new syntax, might switch to it at some point but already jumped throught the various hoops to get the older syntax working so would actually need to rethink how I'm constructing my statusline since it's very over engineered and would need to be refactored to the other style, and I'm desperately trying to manage my time better and spend less of it on obscure nvim stuff 😆

**Comment by windwp** [comment]
@shadmansaleh   why you bother him for that :heart:
I think about convert %= on Lua but I am lazy a bit
that repo is just a demo .use ffi code call from lua to c then use lua to convert to extmark is slow.
if you run animation on that you will see the difference.

I should make that repo archive so nobody bothers me about floatline. :thinking:
