### ISSUE TITLE
Issue with float window width

### ISSUE THREAD

**Issue by mrjones2014** [windwp/floatline.nvim#2]
It doesn't go all the way across. It only goes across about a sixth of the window for some reason.

![CleanShot-2021-09-29-at-07 58 30](https://user-images.githubusercontent.com/8648891/135264088-3a2c56b2-75f8-478d-8988-90e413a290a0.png)

**Comment by windwp** [comment]
is that issue still happen?

**Comment by windwp** [comment]
you are using lualine right? I test and it work
can you share your config
then @shadmansaleh  can help :)

**Comment by mrjones2014** [comment]
Config here: https://github.com/mrjones2014/dotfiles/blob/master/.config/nvim/lua/configure/lualine.lua

**Comment by windwp** [comment]
sorry I try your config but it working.

lol i see you see my windline.
you can't  run a plenay job inside an component to get branch name. It run every time  statusline redraw  :cry:

**Comment by mrjones2014** [comment]
I tried windline, the config is still there but I disabled it cause I had too many issues with it. I used a plenary job because the built-in git branch component depends on the gitsigns plugin which I don't use (also this dependency is not documented).

My floatline config is working for you?

**Comment by shadmansaleh** [comment]
@mrjones2014 is your fork branched from hoob3rt/lualine ? if so can try on [shadmansaleh/lualine.nvim](https://github.com/shadmansaleh/lualine.nvim) and see if it works ?

**Comment by shadmansaleh** [comment]
Probably I just tried his config it works fine for me .

**Comment by windwp** [comment]
yeah my mistake it work for me on macos too 👍

**Comment by shadmansaleh** [comment]
Can you check what `:echom &columns` say ?
put a print after [this line](https://github.com/windwp/floatline.nvim/blob/d36702341cef923f9b34228d818ad78ae6e7797c/lua/floatline/ffi_convert.lua#L83) and check what's the value of `ffi.string(stl_buf)`

**Comment by mrjones2014** [comment]
`:lua print(vim.go.columns)` prints 280

I tried editing the file locally from `~/.local/share/nvim/site/pack/packer/start/floatline.nvim/lua/floatline/ffi_convert.lua`, but it didn't seem to print anything. Do I need to fork the repo and install the plugin from my fork?

**Comment by mrjones2014** [comment]
`vim.o.columns` is the same value, 280.

output of print(vim.inspect(status_str), #status_str)`

![CleanShot-2021-10-06-at-13 19 58](https://user-images.githubusercontent.com/8648891/136252671-035490ed-e2c1-480a-bbb6-1c235c57b628.png)

`floatline_on_resize` is never being called for me.

**Comment by mrjones2014** [comment]
manually calling `require('floatline').floatline_on_resize()` doesn't work either.

**Comment by shadmansaleh** [comment]
What's shown if you do ?

```vim
:set stl=left%=right
```

Also what arch, os, terminal, neovim version are you using ?

**Comment by mrjones2014** [comment]
![CleanShot-2021-10-06-at-14 13 12](https://user-images.githubusercontent.com/8648891/136259902-a904bdb1-754c-4f2a-86cd-f6d7b5f717e9.png)

Changing that line doesn't affect anything.

I'm using an M1 Mac Mini (so ARM architecture), macOS 11.6, Kitty version 0.21.2, Neovim 0.5.1.

**Comment by mrjones2014** [comment]
I assume the `%=` is some kind of separator. Where can I find docs on that?

**Comment by shadmansaleh** [comment]
> I assume the %= is some kind of separator. Where can I find docs on that?

`:h stl`

yours is acting as if vim.go.columns is 0 in that line. I see no reason for that . I assume it's a issue where lua number doesn't get properly converted to c int . Since apples arm toolchain is fairely new it's possible this occures because of some inconsistency there .

I'm out of ideas . I don't think I can do anything about this.

**Comment by windwp** [comment]
I just joke to  @shadmansaleh :smiley: :smiley: :smiley:

**Comment by rawhat** [comment]
I don't know how helpful this will be since it seems to be an oddity, but I also have this.  I am running in WSL2 with WezTerm.

This happens consistently with `lualine`.  With `windline` it seems to work when I add it and run `:PackerSync`.  If I then run `:PackerCompile`, it actually disappears.  I then can run `:WindLineFloatToggle`, and it seems to go full size again.  Unfortunately I can't do that with `lualine`, so not sure if I can use that combo at all.

I tried adding an `vim.api.nvim_command("WindLineFloatToggle")` to the packer config for `windline`, but that causes some other weird issues.

I can link my config as needed.  I also have tried this with a limited packer setup with the following `init.lua` that has the same issue:

```lua
vim.cmd([[packadd packer.nvim]])

return require("packer").startup(function(use)
	use("wbthomason/packer.nvim")

	use({
		"EdenEast/nightfox.nvim",
		config = function()
			require("nightfox").load()
		end,
	})

	use({
		"nvim-treesitter/nvim-treesitter",
		config = function()
			require("nvim-treesitter.configs").setup({
				ensure_installed = "all",
				highlight = {
					enable = true,
				},
			})
		end,
	})

	use({
		"windwp/windline.nvim",
		requires = {
			{
				"windwp/floatline.nvim",
				config = function()
					require("floatline").setup()
				end,
			},
		},
		config = function()
			require("wlsample.evil_line")
		end,
	})
end)
```

(Not actually an) edit:  while trying to grab a screenshot for this... I realized if I have the window in any orientation other than fully maximized, it works just fine.  If I maximize the window, it shrinks down to the smaller size.

I can live with having to run the command on load if I have to.  Just curious if I can provide any additional information to help debug this issue.  Or even to narrow it down to something separate that isn't this plugin!  I really like it, so I will probably keep using it.  Thank you!

**Comment by shadmansaleh** [comment]
I think I get it now . [buf_len](https://github.com/windwp/floatline.nvim/blob/d36702341cef923f9b34228d818ad78ae6e7797c/lua/floatline/ffi_convert.lua#L42) needs to be larger then columns and when it's not this bug occurs since nvim can't fit the expanded stl in buf . @mrjones2014 @rawhat try increasing buflen from 256 something larger like 1024 in [here](https://github.com/windwp/floatline.nvim/blob/d36702341cef923f9b34228d818ad78ae6e7797c/lua/floatline/ffi_convert.lua#L35) and [here](https://github.com/windwp/floatline.nvim/blob/d36702341cef923f9b34228d818ad78ae6e7797c/lua/floatline/ffi_convert.lua#L42) see if this resolves the issue.

cc @windwp

**Comment by windwp** [comment]
closing it I use a api from neovim so it that issue still happen report an issue on neovim.
